name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        submodules: 'recursive'
        
    - name: Build the Docker image
      shell: pwsh
      working-directory: src
      run: |
        dotnet tool install -g nbgv  
        .\DockerBuild.ps1
